### ISSUE TITLE
Compatibility with Sinytra connector

### ISSUE THREAD

**Issue by noukhern** [Lyinginbedmon/TricksyFoxes#7]
I wonder if the dev or anyone else has managed to make this mod work on forge? I have tried with what seems to be the bare minimum (Sinytra, Connector extra, Cardinal Components and Tricksy Foxes) but I cant get past the world load screen.

**Comment by Lyinginbedmon** [comment]
There are no current plans to port the mod to Forge, in part because I'm very busy and in part because the mod was started as a way for me to get accustomed to how Fabric works compared to Forge.

However, if you post a crash report or error log I'll happily investigate to see if I can get it to work through Sinytra.

**Comment by noukhern** [comment]
Sorry. I knew you weren't porting to forge, the post was solely about Sinytra. 

In any case, after trying things I managed to fix it. The problem is not within tricksy foxes but Cardinal Components it seems. It doesnt work at all on Sinytra Connector beta36. Swapping to beta34 makes it work flawlessly. Hopefully further versions will fix the issue.

By the way. Thanks for making the mod, I like looking at your dev posts on the hex casting discord, and programming foxes is cute.
